Expense_Manager/Controllers/AddCategoryController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL.DataClasses;
namespace Expense_Manager.Controllers
{
    [Authorize]
    public class AddCategoryController : Controller
    {
        // GET: AddCategory
        CategoryBLL categoryBLL = new CategoryBLL();
        Models.Category CategoryModel = new Models.Category();



        public ActionResult Add_Category()
        {
            string userid = "";
            HttpCookie cookieObj = HttpContext.Request.Cookies.Get("info");
            if (cookieObj != null)
            {
                userid = cookieObj["id"];
            }
            ViewBag.list= categoryBLL.GetCategoryList(userid);     //Here using viewdata to send list of categories
            return View();                                                   //this is one of the method to display multiple model in view
        }




        [HttpPost]
        public ActionResult SaveCategory(Models.Category category)
        {
            int result = 0;
            bool success = false;
            string message = "Error";
            if(ModelState.IsValid)
            {
                result = categoryBLL.AddCategory(category);
                if (result == 1)
                {
                    message = "Category Added Successfully!";
                    success = true;
                }
                else if(result == 2){
                    message = "Category Already Exist! Please give another category name.";
                    success = false;
                }else if (result == 0)
                {
                    message = "Category not added!";
                    success = false;
                }
                else
                {
                    message = "error";
                }
            }
            return Json(new { success = success, responseText =message }, JsonRequestBehavior.AllowGet);
        }




        [HttpPost]
        public ActionResult DeleteCategory(Models.Category category)
        {
            int result =categoryBLL.DeleteCategory(category.id);
            if (result == 1)
            {
                return Json(new { success = true, responseText = "" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, responseText = "Error in Deleting category !" }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult EditCategory(int id,string name)
        {
            if (id > 0 && name != null)
            {
                int result=categoryBLL.EditCategory(id, name);
                if (result == 1) {
                    return Json(new { success = true, responseText = "" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { success = false, responseText = "Error in Editing Category !" }, JsonRequestBehavior.AllowGet);
        }

    }
}

Expense_Manager/Controllers/AddExpenseOrIncomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL.DataClasses;

namespace Expense_Manager.Controllers
{
    [Authorize]
    public class AddExpenseOrIncomeController : Controller
    {

        CategoryBLL categoryBLL = new CategoryBLL();
        ExpenseIncomeBLL ExInObj = new ExpenseIncomeBLL();
        AccountController account = new AccountController();

        // GET: AddExpenseOrIncome
        [HttpGet]
        public ActionResult Add_expense()
        {
            BindDropList();
            return View();
        }

        public void BindDropList()
        {
            int userid = 0;
            HttpCookie cookieObj = HttpContext.Request.Cookies.Get("info");
            if (cookieObj != null)
            {
                userid = Convert.ToInt32(cookieObj["id"]);
            }
            List<Models.Category> categoryList = new List<Models.Category>();
            if (userid > 0)
            {
                categoryList = categoryBLL.GetCategoryList(userid.ToString());
            }
            ViewBag.list = categoryList;
        }

        /*
        [HttpGet]
        public ActionResult GetCategories()
        {
            //int id = account.GetUserId();
            int userid = 0;
            HttpCookie cookieObj = HttpContext.Request.Cookies.Get("info");
            if (cookieObj != null)
            {
                userid = Convert.ToInt32(cookieObj["id"]);
            }
            List<Models.Category> categoryList = new List<Models.Category>();
            if (userid > 0)
            {
                categoryList = categoryBLL.GetCategoryList(userid.ToString());
                return Json(categoryList, JsonRequestBehavior.AllowGet);
            }

            return Json("", JsonRequestBehavior.AllowGet);
        }
        */

        [HttpPost]
        public ActionResult Add_record(Models.Records rec)
        {
            int result = 0;
            bool success = false;
            string message = "Error";
            BindDropList();
            if (ModelState.IsValid && rec.userid>0)
            {
                result=ExInObj.AddRecord(rec);
                success = true;
                message = "Successfully saved record !";
                return Json(new { success = success, responseText = message }, JsonRequestBehavior.AllowGet);
            }
            
            return View("Add_Expense");
        }

    }
}

Expense_Manager/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Expense_Manager.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult UserProfile()
        {
            return View();
        }
    }
}

Expense_Manager/Views/Shared/_Master_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Dashboard - Brand</title>
    <link rel="stylesheet" href='@Url.Content("~/Content/css/bootstrap.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Content/css/dh-card-image-left-dark.css")'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href='@Url.Content("~/Content/css/Customizable-Carousel-swipe-enabled.css")'>
    <link rel="stylesheet" href='@Url.Content("~/fonts/fontawesome-all.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/fonts/font-awesome.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/fonts/fontawesome5-overrides.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Content/css/dataTables.bootstrap.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Content/css/Login-Form-Clean.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Content/css/Registration-Form-with-Photo.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Content/css/Data-Table.css")'>
</head>

<body id="page-top">

    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="@Url.Action("Add_Expense", "AddExpenseOrIncome")">
                    <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-dollar-sign"></i></div>
                    <div class="sidebar-brand-text mx-1"><span>Expense Diary</span></div>
                </a>
                <hr class="sidebar-divider my-0" />
                <ul class="nav navbar-nav text-light" id="accordionSidebar">
                    <li role="presentation" class="nav-item"><a class="nav-link active" href="@Url.Action("Add_Expense", "AddExpenseOrIncome")"><i class="far fa-plus-square"></i><span>Add Expense/Income</span></a></li>
                    <li role="presentation" class="nav-item"><a class="nav-link active" href="@Url.Action("Add_Category", "AddCategory")"><i class="fas fa-list-ul"></i><span>Add Categories</span></a></li>
                    <li role="presentation" class="nav-item"><a class="nav-link active" href="@Url.Action("Reports", "Reports")"><i class="far fa-file-alt"></i><span>Reports</span></a></li>
                    <li role="presentation" class="nav-item"><a class="nav-link active" href="@Url.Action("Settings", "Settings")"><i class="fas fa-cog"></i><span>Settings</span></a></li>
                    <li role="presentation" class="nav-item"><a class="nav-link active" href="@Url.Action("About", "Home")"><i class="fas fa-info-circle"></i><span> About</span></a></li>
                </ul>

                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid">
                        <label id="ScreenLabel"><strong>@ViewBag.Title</strong></label>
                        <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        <ul class="nav navbar-nav flex-nowrap ml-auto">
                            <li class="nav-item dropdown d-sm-none no-arrow">
                                <a data-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link" href="#"><i class="fas fa-search"></i></a>
                                <div role="menu" class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto navbar-search w-100">
                                        <div class="input-group">
                                            <input type="text" class="bg-light form-control border-0 small" placeholder="Search for ..." />
                                            <div class="input-group-append"><button class="btn btn-primary py-0" type="button"><i class="fas fa-search"></i></button></div>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <li role="presentation" class="nav-item dropdown no-arrow mx-1">
                                <div class="nav-item dropdown no-arrow">
                                    <a data-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link" href="#"><span class="badge badge-danger badge-counter">3+</span><i class="fas fa-bell fa-fw"></i></a>
                                    <div role="menu" class="dropdown-menu dropdown-menu-right dropdown-list dropdown-menu-right animated--grow-in">
                                        <h6 class="dropdown-header">alerts center</h6>
                                        <a class="d-flex align-items-center dropdown-item" href="#">
                                            <div class="mr-3">
                                                <div class="bg-primary icon-circle"><i class="fas fa-file-alt text-white"></i></div>
                                            </div>
                                            <div>
                                                <span class="small text-gray-500">December 12, 2019</span>
                                                <p>A new monthly report is ready to download!</p>
                                            </div>
                                        </a>
                                        <a class="d-flex align-items-center dropdown-item" href="#">
                                            <div class="mr-3">
                                                <div class="bg-success icon-circle"><i class="fas fa-donate text-white"></i></div>
                                            </div>
                                            <div>
                                                <span class="small text-gray-500">December 7, 2019</span>
                                                <p>$290.29 has been deposited into your account!</p>
                                            </div>
                                        </a>
                                        <a class="d-flex align-items-center dropdown-item" href="#">
                                            <div class="mr-3">
                                                <div class="bg-warning icon-circle"><i class="fas fa-exclamation-triangle text-white"></i></div>
                                            </div>
                                            <div>
                                                <span class="small text-gray-500">December 2, 2019</span>
                                                <p>Spending Alert: We&#39;ve noticed unusually high spending for your account.</p>
                                            </div>
                                        </a><a class="text-center dropdown-item small text-gray-500" href="#">Show All Alerts</a>
                                    </div>
                                </div>
                            </li>
                            <li role="presentation" class="nav-item dropdown no-arrow mx-1">
                                <div class="shadow dropdown-list dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown"></div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li role="presentation" class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow">
                                    @{
                                        string fname = "";
                                        string lname = "";
                                        HttpCookie cookieObj = Context.Request.Cookies.Get("info");
                                        if (cookieObj != null)
                                        {
                                            fname = cookieObj["fname"];
                                            lname = cookieObj["lname"];
                                        }
                                    }
                                    <a data-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link" href="#">
                                        <span class="d-none d-lg-inline mr-2 text-gray-600 small">
                                            Hi! @fname.ToUpper() @lname.ToUpper()
                                        </span><img class="border rounded-circle img-profile" src='@Url.Content("~/images/avatars/avatar1.jpeg")' />
                                    </a>
                                    <div role="menu" class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                        <a role="presentation" class="dropdown-item" href="@Url.Action("UserProfile", "Profile")"><i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile</a><a role="presentation" class="dropdown-item" href="@Url.Action("Settings", "Settings")"><i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i> Settings</a>
                                        <a role="presentation" class="dropdown-item" href="#"><i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i> Activity log</a>
                                        <div class="dropdown-divider"></div><a role="presentation" class="dropdown-item" href="@Url.Action("Signout", "Account")"><i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>

                <! -- Body start here -->
                <div>
                    @RenderBody()
                </div>

            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Copyright © Brand 2019</span></div>
                </div>
            </footer>
        </div><a id="gotoTopWidget" class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src='@Url.Content("~/Scripts/js/Customizable-Carousel-swipe-enabled.js")'></script>
    @*<script src="https://code.jquery.com/jquery-1.12.4.js"></script>*@
    <script src='@Url.Content("~/Scripts/js/jquery.min.js")'></script>
    <script src="~/Scripts/js/AddCategory.js"></script>>
    <script src="~/Scripts/js/AddExpenseIncome.js"></script>
    <script src='@Url.Content("~/Scripts/js/jquery-ui.js")'></script>
    <script src='@Url.Content("~/Scripts/js/bootstrap.min.js")'></script>
    <script src='@Url.Content("~/Scripts/js/scripts.js")'></script>
    <script src='@Url.Content("~/Scripts/js/theme.js")'></script>
    <script src='@Url.Content("~/Scripts/js/jquery.dataTables.min.js")'></script>
    <script src='@Url.Content("~/Scripts/js/dataTables.bootstrap.min.js")'></script>
    <script src='@Url.Content("~/Scripts/js/jquery.easing.js")'></script>
</body>

</html>